# Isaac Sim + Pegasus + ArduPilot SITL Development Environment
#
# IMPORTANT: Before running GUI mode, execute: xhost +local:
#
# Usage:
#   # GUI Mode - requires X11 forwarding
#   xhost +local:  # Allow local X11 connections (run once per session)
#   podman-compose up isaac-sim-gui
#
#   # Headless Mode - for CI/CD or remote servers
#   podman-compose up isaac-sim-headless
#
#   # With MAVProxy GCS
#   podman-compose --profile gcs up isaac-sim-gui
#
# Interactive development:
#   podman exec -it isaac-sim-dev bash

services:
  # ============================================
  # GUI Mode - Full graphical interface
  # ============================================
  isaac-sim-gui:
    container_name: isaac-sim-dev
    image: nvcr.io/nvidia/isaac-sim:4.2.0

    # GPU passthrough via CDI
    devices:
      - nvidia.com/gpu=all

    # Override default headless entrypoint to run GUI app with Pegasus extension
    entrypoint: ["/bin/bash", "-c", "/isaac-sim/license.sh && /isaac-sim/privacy.sh && /isaac-sim/kit/kit /isaac-sim/apps/omni.isaac.sim.kit --ext-folder /isaac-sim/apps --ext-folder /workspace/PegasusSimulator/extensions --enable pegasus.simulator --allow-root"]

  # ============================================
  # Test Mode - Run ArduPilot test script
  # ============================================
  isaac-sim-test:
    container_name: isaac-sim-test
    image: nvcr.io/nvidia/isaac-sim:4.2.0

    # GPU passthrough via CDI
    devices:
      - nvidia.com/gpu=all

    # Run python.sh with Pegasus extension in Kit path
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /isaac-sim/license.sh && /isaac-sim/privacy.sh &&
        echo "Installing pymavlink for ArduPilot backend..." &&
        /isaac-sim/python.sh -m pip install pymavlink --quiet &&
        export PYTHONPATH=/workspace/PegasusSimulator/extensions/pegasus.simulator:$$PYTHONPATH &&
        /isaac-sim/python.sh /workspace/scripts/test_ardupilot_pegasus.py

    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      - DISPLAY=${DISPLAY:-:0}
      - HEADLESS=0
      - PYTHONUNBUFFERED=1
      - ISAACSIM_PATH=/isaac-sim
      - OMNI_KIT_ACCEPT_EULA=YES
      - ROS_DOMAIN_ID=42

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/share/vulkan/icd.d/nvidia_icd.json:/usr/share/vulkan/icd.d/nvidia_icd.json:ro
      - /usr/share/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d:ro
      - isaac-cache:/isaac-sim/kit/cache/Kit
      - isaac-data:/root/.local/share/ov
      - isaac-logs:/root/.nvidia-omniverse/logs
      - ./:/workspace:z
      - ${XAUTHORITY:-/run/user/1000/.mutter-Xwaylandauth.0J83H3}:/root/.Xauthority:ro

    network_mode: host
    ipc: host
    security_opt:
      - label=disable

    stdin_open: true
    tty: true

    working_dir: /isaac-sim
    profiles:
      - test

  # ============================================
  # Headless Mode - No GUI, for training/CI
  # ============================================
  isaac-sim-headless:
    container_name: isaac-sim-headless
    image: nvcr.io/nvidia/isaac-sim:4.2.0

    # GPU passthrough via CDI
    devices:
      - nvidia.com/gpu=all

    # Uses default entrypoint (runheadless.native.sh)

    environment:
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
      # Headless mode - no display needed
      - DISPLAY=
      - HEADLESS=1
      # Isaac Sim settings
      - ISAACSIM_PATH=/isaac-sim
      - OMNI_KIT_ACCEPT_EULA=YES
      # ROS 2 domain isolation
      - ROS_DOMAIN_ID=42

    volumes:
      # Vulkan ICD still needed for GPU compute
      - /usr/share/vulkan/icd.d/nvidia_icd.json:/usr/share/vulkan/icd.d/nvidia_icd.json:ro
      # Shader cache
      - isaac-cache:/isaac-sim/kit/cache/Kit
      - isaac-data:/root/.local/share/ov
      - isaac-logs:/root/.nvidia-omniverse/logs
      # Workspace mount
      - ./:/workspace:z

    network_mode: host
    ipc: host

    stdin_open: true
    tty: true

    working_dir: /isaac-sim

  # ============================================
  # ArduPilot SITL - Software-in-the-Loop
  # ============================================
  # NOTE: ArduPilot is installed in the Isaac Sim container.
  # Run SITL from inside the Isaac Sim container:
  #   podman exec -it isaac-sim-dev bash
  #   cd /ardupilot && Tools/autotest/sim_vehicle.py -v ArduCopter -f JSON:127.0.0.1 --speedup 1 --out udp:127.0.0.1:14550
  ardupilot-sitl:
    container_name: ardupilot-sitl
    image: docker.io/ardupilot/ardupilot-dev-base:latest
    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /ardupilot
    # SITL with JSON backend for Isaac Sim/Pegasus integration
    # JSON port 9002 for sensor data from Isaac Sim (sent by Pegasus)
    # MAVLink port 14550/14551 for GCS connection
    # Note: First run will clone ArduPilot repo (~2GB) and build SITL (~5-10 min)
    volumes:
      - ardupilot-src:/ardupilot
    command: >
      /bin/bash -c "
      if [ ! -f /ardupilot/Tools/autotest/sim_vehicle.py ]; then
        echo 'Cloning ArduPilot repository...';
        git clone --recurse-submodules https://github.com/ArduPilot/ardupilot.git /ardupilot;
      fi &&
      cd /ardupilot &&
      echo 'Starting ArduCopter SITL with JSON backend...' &&
      echo 'Building if needed...' &&
      ./waf configure --board sitl && ./waf copter &&
      echo 'Starting SITL binary directly...' &&
      build/sitl/bin/arducopter --model JSON:127.0.0.1 --speedup 1 --sim-address=127.0.0.1 -I0 --defaults /ardupilot/Tools/autotest/default_params/copter.parm
      "
    profiles:
      - sitl

  # ============================================
  # MAVProxy - Ground Control Station interface
  # ============================================
  mavproxy:
    container_name: mavproxy-dev
    image: docker.io/ardupilot/ardupilot-dev-base:latest
    environment:
      - MASTER=udp:127.0.0.1:14550
    network_mode: host
    command: >
      mavproxy.py
      --master=udp:127.0.0.1:14550
      --out=udp:127.0.0.1:14551
      --console
    profiles:
      - gcs

volumes:
  isaac-cache:
    driver: local
  isaac-data:
    driver: local
  isaac-logs:
    driver: local
  ardupilot-src:
    driver: local
